export default {
  level: 0,
  nodeID: "0",
  nodeName: "根节点",
  display: true,
  childCount: 1,
  childNodeList: [
    {
      level: 1,
      nodeID: "1",
      nodeName: "计划审核",
      display: true,
      childCount: 4,
      childNodeList: [
        {
          level: 2,
          nodeID: "1000042",
          nodeName: "化妆品分级-1000042",
          display: true,
          childCount: 1,
          childNodeList: [
            {
              level: 3,
              nodeID: "1695981233052685",
              nodeName: "计划拒绝--化妆品",
              display: true,
              childCount: 4,
              childNodeList: [
                {
                  level: 4,
                  nodeID: "1644827368671240",
                  nodeName: "机",
                  display: true,
                  childCount: 40,
                  childNodeList: [
                    {
                      level: 5,
                      nodeID: "25001",
                      nodeName: "含有虚假宣传及误导相关内容描述",
                      display: false,
                      childCount: 0,
                      childNodeList: null,
                    },
                    {
                      level: 5,
                      nodeID: "2500eewwe1",
                      nodeName: "含有虚假宣传及误导相关内容描述",
                      display: false,
                      childCount: 0,
                      childNodeList: null,
                    },
                    {
                      level: 5,
                      nodeID: "20020001",
                      nodeName: "低俗",
                      display: false,
                      childCount: 0,
                      childNodeList: null,
                    },
                  ],
                },
                {
                  level: 4,
                  nodeID: "16448273fdfdfd686ffdfd71240",
                  nodeName: "机审拒绝-黑图fdfdfd库dsadddddddddddddddddddddddd",
                  display: true,
                  childCount: 40,
                  childNodeList: [
                    {
                      level: 5,
                      nodeID: "250fdfd01",
                      nodeName: "含有虚假宣传及误导相关内fdffd容描述",
                      display: false,
                      childCount: 0,
                      childNodeList: null,
                    },
                    {
                      level: 5,
                      nodeID: "3332235",
                      nodeName: "低俗",
                      display: false,
                      childCount: 0,
                      childNodeList: null,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          level: 2,
          nodeID: "10000ddsds42",
          nodeName: "化妆品dsdsds分级-1000042",
          display: true,
          childCount: 1,
          childNodeList: [
            {
              level: 3,
              nodeID: "16959sddsds81233052685",
              nodeName: "计划拒绝--化妆品",
              display: true,
              childCount: 4,
              childNodeList: [
                {
                  level: 4,
                  nodeID: "16448273sdsdd4334343434434343",
                  nodeName: "机审拒绝-黑图库",
                  display: true,
                  childCount: 40,
                  childNodeList: [
                    {
                      level: 5,
                      nodeID: "11",
                      nodeName: "含有虚假宣传及误导相关内容描述",
                      display: false,
                      childCount: 0,
                      childNodeList: null,
                    },
                    {
                      level: 5,
                      nodeID: "112",
                      nodeName: "低俗",
                      display: false,
                      childCount: 0,
                      childNodeList: null,
                    },
                  ],
                },
                {
                  level: 4,
                  nodeID: "1232332323232322",
                  nodeName: "机审拒绝-黑图fdfdfd库",
                  display: true,
                  childCount: 40,
                  childNodeList: [],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
